name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-24.04-arm
            system: aarch64-linux
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@1d87d45818068401a10cf16bdc5f00b24994a83f
      - uses: cachix/cachix-action@v15
        with:
          name: pr0d1r2
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop -c nix-unit --flake .#tests
      - run: nix flake check --no-build
